version: '3.9'

services:
  api: &main_app
    ports:
    - "8000:8000"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
#    image: reverse1999_damage_calculator:${REVERSE1999_DAMAGE_CALCULATOR_VERSION:-latest}
    image: reverse1999_damage_calculator
    restart: always
#    env_file:
#      - .env
#    environment:
#      REVERSE1999_DAMAGE_CALCULATOR_HOST: 0.0.0.0
