version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: reverse1999_damage_calculator:${REVERSE1999_DAMAGE_CALCULATOR_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      REVERSE1999_DAMAGE_CALCULATOR_HOST: 0.0.0.0
